# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Core dependency
gem 'active_data_flow-core-core', path: 'core_core'

# Development dependencies
group :development, :test do
  gem 'rspec'
end
